### PR TITLE
Update bboxes

### PR DESCRIPTION
**Pull request by pmoris**
Tweaked the bounding boxes slightly to work on the current menu. Might require review and further monitoring.

The parsing_pdf function also causes an index error when the bbox captures too few/many prices (or an uneven amount perhaps?).

```
for date, (i, item) in itertools.product(dates, enumerate(menu_items)):
    menu[(date, campus, '{}{}'.format(menu_type, i + 1 if len(menu_items) > 1 else ''))] = (item, price[i * 2], price[i * 2 + 1])

Traceback (most recent call last):
  File "komida_parser.py", line 262, in <module>
    url = get_menu_url("cmi")
  File "komida_parser.py", line 186, in parse_pdf
    for date, (i, item) in itertools.product(dates, enumerate(menu_items)):
IndexError: list index out of range

---

# print((date_key, menu_type), (bb_menu, bb_price))
# (None, 'pasta') ((350, 125, 485, 205), (480, 125, 555, 205))
# salad-bar en frieten Pasta bolognaise of Pasta
# € 6,20 € 3,40/ € 4,20 of
# [6.2, 3.4, 4.2]
```

The `(item, price[i * 2], price[i * 2 + 1])` caused an error for the price of pasta menu here.

### CODE REVIEW

**Comment by bittremieux** [comment]
Yes, obviously the `+ 1` causes an IndexError if there are an uneven number of prices. We should probably be a bit more robust there. But more importantly, parse the PDF properly.

**Comment by JoeyDP** [comment]
> We should probably be a bit more robust there. But more importantly, parse the PDF properly.

A while ago I talked to the crew of Komida. They said they were working on a new platform for their menus which would include a public API for external applications. Let's hope they make good on that promise sometime soon :).

**Comment by JoeyDP** [comment]
PS: This is how I 'fixed' the price index issue. It simply repeats the last prices it was able to parse. 
```
for date, (i, item) in itertools.product(dates, enumerate(menu_items)):
    prices = (price[i * 2], price[i * 2 + 1]) if len(price) > 2*i+1 else (price[-2], price[-1])
    menu[(date, campus, '{}{}'.format(menu_type, i + 1 if len(menu_items) > 1 else ''))] = (item, *prices)
```

**Comment by bittremieux** [comment]
Indeed, I also talked to them and they were very supportive of komidabot. They also mentioned they'd get me some special access to the data but unfortunately no progress on that front for several months now.

**Pull request closed without merging**
